# Generated by Django 5.2.1 on 2025-05-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longurl', models.URLField(max_length=2000)),
                ('shorturl', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
