# Generated by Django 5.2.1 on 2025-06-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataurl',
            name='shorturl',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
